### ISSUE TITLE
Improve responsiveness on homepage

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/rockarch.org#46]
Call to action section layout on homepage requires improved responsiveness

**Comment by helrond** [comment]
<img width="950" alt="Screen Shot 2019-08-05 at 9 46 55 AM" src="https://user-images.githubusercontent.com/607621/62469354-177b1400-b766-11e9-9064-8427a7d1bca4.png">
Is this what you're referring to @HaSistrunk?

**Comment by HaSistrunk** [comment]
Yes, that's what I was seeing.
